"""Add user role to the User

Revision ID: 6d0f88486037
Revises: 37cd61fe149e
Create Date: 2025-07-30 19:43:00.999147

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0f88486037'
down_revision: Union[str, Sequence[str], None] = '37cd61fe149e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum('USER', 'ADMIN', name='userrole')

def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum.create(op.get_bind())
    # --- END OF FIX ---
    
    # 2. Now, add the new 'role' column using the type we just created.
    op.add_column('user', sa.Column('role', user_role_enum, nullable=False, server_default='USER'))
    
    # 3. Drop the old 'is_superuser' column.
    op.drop_column('user', 'is_superuser')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
